POLITIC_QUESTIONS = {
    'q1': "El gobierno debería redistribuir la riqueza de los ricos entre los pobres",
    'q2': "Debemos pagar la sanidad de las personas extranjeras (Sanidad Pública Universal)",
    'q3': "Las pensiones deberían ser privadas y no públicas, cada uno debería ahorrar para su jubilación",
    'q4': "Es legítimo que los países favorezcan su propia religión antes que las de los demás",
    'q5': "Solo los catalanes deberían votar y decidir sobre la independencia de Cataluña",
    'q6': "Es suficiente con que una persona se autoperciba mujer para serlo",
    'q7': "En algunos casos, la pena de muerte debería ser una opción",
    'q8': "Crees en la libre circulación entre países y la acogida de inmigrantes",
    'q9': "Existe una cierta relación entre delincuencia y ciertos colectivos culturales",
    'q10': "Se debe priorizar la natalidad de los españoles frente a la de los inmigrantes",
    'q11': "La prostitución debería ser legalizada",
    'q12': "Las personas que renuncian a un trabajo no deberían recibir ayudas por desempleo",
    'q13': "Solo deberíamos acoger inmigrantes con edades comprendidas entre 18 y 40 años",
    'q14': "El impuesto de sucesiones debería ser eliminado",
    'q15': "Crees en una Renta Básica Universal para todos los ciudadanos",
    'q16': "Sindicatos y partidos políticos deben recibir subvenciones del estado",
}
