# Generated by Django 5.0.7 on 2024-08-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_hat", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("survey", "id")},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
    ]
