# Generated by Django 5.0.7 on 2024-08-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_hat", "0003_rename_result1_answer_question1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="religion",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="sex",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
