# Generated by Django 5.0.7 on 2024-08-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_hat", "0004_survey_age_survey_religion_survey_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question11",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="question12",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="question13",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
