# Generated by Django 5.0.7 on 2024-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_hat", "0005_answer_question11_answer_question12_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="age",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="religion",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="sex",
            field=models.BooleanField(null=True),
        ),
    ]
