# Generated by Django 5.0.7 on 2024-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_hat", "0006_alter_survey_age_alter_survey_religion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="description",
            field=models.TextField(max_length=180),
        ),
        migrations.AlterField(
            model_name="survey",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
