# Generated by Django 5.0.7 on 2024-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_hat", "0007_alter_survey_description_alter_survey_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(max_length=150),
        ),
    ]
